trigger:
  branches:
    include:
    - master

pr:
- master

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --upgrade pytest
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m pip install -e .
    displayName: 'Install package'

  - script: |
      python -m pytest
    displayName: 'Tests with pytest'


- job: 'macOS'
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --upgrade pytest
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m pip install -e .
    displayName: 'Install package'

  - script: |
      python -m pytest
    displayName: 'Tests with pytest'
