trigger:
  branches:
    include:
    - master

pr:
- master

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --upgrade pytest
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m pip install -e .
    displayName: 'Install package'

  - script: |
      python -m pytest
      python -m tdub apply-gennpy
      python -m tdub rex-pulls
      python -m tdub rex-stacks
      python -m tdub train-fold
      python -m tdub train-optimize
    displayName: 'Tests with pytest and run CLI'


- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --upgrade pytest
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m pip install -e .
    displayName: 'Install package'

  - script: |
      python -m pytest
      python -m tdub apply-gennpy
      python -m tdub rex-pulls
      python -m tdub rex-stacks
      python -m tdub train-fold
      python -m tdub train-optimize
    displayName: 'Tests with pytest and run CLI'
