name: PyPI-publish

on:
  push:

jobs:
  build-and-publish:
    name: build distribution and publish to pypi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install wheel and SDist requirements
    - name: Build
      run: >
        python -m pip install pip wheel build -U
        python -m build
