name: Linux/macOS

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macOS-latest]
        python-version: ["3.9", "3.8"]
    runs-on: ${{matrix.platform}}
    steps:
    - uses: actions/checkout@v3
    - name: setup Python ${{matrix.python-version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
    - name: install deps
      run: |
        pip install pip wheel build -U
        pip install .
        pip install pytest
        pip list
    - name: run pytest
      run: |
        python -m tdub --help
        python -m pytest
